#ifndef __GLOBAL_CONSTANTS_H__
#define __GLOBAL_CONSTANTS_H__


#define CPU_SPEED_HZ 4000000

#define VIDEO_MODE0_CLICKS 216
#define VIDEO_MODE1_CLICKS 4560
#define VIDEO_MODE2_CLICKS 77
#define VIDEO_MODE3_CLICKS 172

#define VIDEO_NUM_LINES 154
#define VIDEO_DRAW_LINES 144
#define VIDEO_VBLANK_LINES 10

#define CLICKS_PER_REFRESH (VIDEO_DRAW_LINES * (VIDEO_MODE0_CLICKS + VIDEO_MODE2_CLICKS + VIDEO_MODE3_CLICKS) + VIDEO_MODE1_CLICKS)

#define VIDEO_REFRESH_RATE 60

#endif
